### ISSUE TITLE
[boschshc] Support for Groundfloor Heating Controller (Fussbodenheizung)

### ISSUE THREAD

**Issue by mike-bike** [openhab/openhab-addons#10767]
Firstly, many thanks to all the good work on the OpenHAB project and the Bosch SHC binding. I have now managed to connect my TwinGuard and some basic channels for the ground floor heating controllers. I have configured them as "Bosch Thermostat" and get temperature readings perfectly fine. Obviously the other channels are not accessible (e.g. Humidity, SetPoint) I do get the following in the log:

16:54:08.594 [DEBUG] [c.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"iconId":"icon_room_bathroom","extProperties":{"humidity":"68.0"},"@type":"room","name":"Badezimmer","id":"hz_1"},{"path":"/devices/roomClimateControl_hz_1/services/TemperatureLevel","@type":"DeviceServiceData","id":"TemperatureLevel","state":{"@type":"temperatureLevelState","temperature":23.1},"deviceId":"roomClimateControl_hz_1"}],"jsonrpc":"2.0"}

Do I need to select another Thing or configure that differently?

Many thanks for your response.

Regards,
Michael

**Comment by coeing** [comment]
Hi @mike-bike ! Thanks for using our binding :) I am happy to hear that it works (mostly) for you.

About your issue: Could you post a link to the device you are trying to connect? Some link from a shopping site or the Bosch website would be sufficient. So we are sure to talk about the same thing.

To set the temperature you will have to add a "Climate Control" thing to openHAB. In your log you see the device id of it: `roomClimateControl_hz_1` . Climate Control devices are virtual devices which are created by the Bosch home controller; one for each room. The temperature can not be set for each thermostat, but only for each climate control device. If you use the Bosch mobile app you will see that it works there the same way.

In our next version there will be a "Wall thermostat" thing which supports a humidity channel beside the temperature channel. That should work for your device.

**Comment by mike-bike** [comment]
Hi Christian, many thanks for the quick and helpful response. I have seen the virtual device but not realized the purpose☹️ I will try that tomorrow. 

One minor issue I have observed is that the temperature readings are NULL for quite a long time - I just have added a 5th wall thermostat. I get values for the first four but not for the new one. Same happened to the four before until suddenly values appeared. Strange! Any idea?

Please find link to the devices in question here https://www.bosch-smarthome.com/de/de/produkte/geraete/raumthermostat-fussbodenheizung/

I‘d assume the WallThermostat will exactly be the right thing I am looking for. I have found that name in the OpenHAB.log as part of the device‘s response.

I am looking forward to the next release. Keep up with the good work. Many thanks again. 

 Kind regards
Michael

**Comment by coeing** [comment]
Hi Michael,

Yes, the stall temperature readings were already reported and are fixed in the next version (see https://github.com/stefan-kaestle/openhab2-addons/issues/66 for some details).

Yes, your device is the wall thermostat (I have no clue who gave it that name instead of using room thermostat ;) ). If you like, check out our repository from time to time, I think we will create a beta version for our next version soon and make it available for download. That way some people can already test it and might find some bugs we can fix before the official release.

**Comment by mike-bike** [comment]
Hi Christian, I just have installed the latest official OpenHAB build 3.1.0. Unfortunately the Wall Thermostat did not make it into the release. I am happy to test a beta version of your binding if you could please direct me to a download link. Otherwise I just will wait until the next milestone release for 3.2.
Thanks or your effort, Michael

**Comment by mike-bike** [comment]
Just seen that the first Milestone release is out and installed 3.2.0 M1. Unfortunately I still don't get any readings from the thermostats. The Twinguard is working perfectly fine. Do you have any idea, what I could do to convince the binding:-) 
Or would I need to wait until the Wall Thermostat thing would become available? Are you still planning to release that including humidity? I am happy to test but would need a bit more instructions. Many thanks.
Regards, Michael

**Comment by coeing** [comment]
Hi @mike-bike ,

A new openHAB release does not necessarily mean that the binding was updated. We did not send our changes to openHAB, so the latest version there is still v1.1. 

But we just created a first release candidate for v1.2. Feel free to use the jar from here: https://github.com/stefan-kaestle/openhab2-addons/releases/tag/v1.2-rc1 to get the latest features. The wall thermostat is in there as well :) You will just have to copy the jar into your openHAB "addons" folder (probably best to uninstall the previous version).

**Comment by mike-bike** [comment]
Many thanks for the quick response. I very understand that a new Openhab release does not necessarily include all new versions of your bindings. Nevertheless, I was hoping…
Anyway, I have now loaded the new version and uninstalled the old binding. Hopefully the new is now installed. At least Karaf is showing that:

openhab> list | grep Bosch
235 │ Active │  80 │ 3.2.0.202107292001    │ openHAB Add-ons :: Bundles :: Bosch Smart Home Binding

Twinguard continous to work as before. For the Thermostats I get the following error:

CONFIGURATION_ERROR 
Request for info of device id=hdm:HomeMaticIP:3014F711A000239D585BCC81 failed with status code 400 and error code ILLEGAL_QUERY_PARAMS

The same error appears for the existing Thermostats as well as for a newly configured Wall Thermostat. Any idea where I should look at? Karaf only shows that one Bosch binding, but honestly I am not sure where to check that no old code is hanging around ...

Regards,
Michael

**Comment by mike-bike** [comment]
Strange message I see in openhab.log

2021-08-02 23:27:01.263 [WARN ] [ty.util.ssl.SslContextFactory.config] - Trusting all certificates configured for ***@***.***[provider=null,keyStore=file:///var/lib/openhab/etc/oss_openhab_binding_192.168.6.43.jks,trustStore=null]
2021-08-02 23:27:01.265 [WARN ] [ty.util.ssl.SslContextFactory.config] - No Client EndPointIdentificationAlgorithm configured for ***@***.***[provider=null,keyStore=file:///var/lib/openhab/etc/oss_openhab_binding_192.168.6.43.jks,trustStore=null]

IP address points to Bosch Bridge. However, my Twinguard seems to be working as normal. I am happy to help with further details, but would require some support what I would need do.

Regards,
Michael

**Comment by mike-bike** [comment]
I probably should not test that late. I had an error in the device ID.

>> id=hdm:HomeMaticIP:3014F711A000239D585BCC81 

Removed id= at the beginning and it now works. Not sure whether the old binding was more flexible or tolerant, but this seems to be it. Will check the other configs….

Sorry for the confusion caused.

**Comment by coeing** [comment]
@mike-bike No problem, glad you found the configuration error yourself :) Let me know if you have any other issues!

**Comment by mike-bike** [comment]
@coeing , I do have 5 wall thermostats and 1 TwinGuard which are all working fine now. Many thanks for your and the teams's effort. I do have a few in-wall switches and door contacts which I plan to integrate shortly as time permits. Any plans to support the camera?

**Comment by coeing** [comment]
@mike-bike @tuxianerDE Sounds good! Hope the version stays stable so we can open the pull request next week! :) 

@mike-bike Support for the camera is not planned right now as we do not have one available in our homes, so it is difficult to test. Could you tell me what functions the camera should support?

**Comment by mike-bike** [comment]
Binding is running perfectly fine. Not doing much fun yet, but I do get constant readings and can watch temp and humidity nicely moving:-) I am going to install some wall switches soon. Unfortunately my new flat does not have automated blinds as the previous had:-( Probably should consider that with the next move:-)

I do not yet own a camera myself. A friend of mine has some and I am considering to buy one. I will talk to him, what features it offers. I could imagine a motion trigger, life picture, and camera control.

**Comment by coeing** [comment]
@mike-bike Please close the issue if the heating controller works for you :)

**Comment by mike-bike** [comment]
Sensors are working for me fine since installing current binding from this repository. Many thanks for the support and good work. Hope it will make it into official OpenHAB release quite soon.

**Comment by mike-bike** [comment]
Done. Sorry for missing that.
