### ISSUE TITLE
[smaenergymeter] Weird PowerIn values with newer firmwares

### ISSUE THREAD

**Issue by Homer-Sim** [openhab/openhab-addons#11497]
Since around two weeks I have this kind of graph (displaying Energy in out)
![grafik](https://user-images.githubusercontent.com/13933431/139659171-195ccb72-2016-4c72-9f3b-cff000426d85.png)

In my DB  I see some weird values
![grafik](https://user-images.githubusercontent.com/13933431/139659391-4c6a7dc9-820c-440f-a2ba-8adb17319c20.png)

Before it worked for years perfectly. All systems/IT were already rebooted but behavior keeps weird.
I am still on OH 2.5 because 3.x is not working for me.

**Comment by sebash42** [comment]
Same issue here with OH3. It does not happen for the solar yield. The inverter also has the correct data

<img width="954" alt="oh3-sma" src="https://user-images.githubusercontent.com/74217095/140436811-0b12fbf9-6d4a-4e1c-a576-96ea5bf75f26.png">
.

**Comment by wborn** [comment]
Perhaps @monnimeter can help with fixing this issue?

**Comment by Homer-Sim** [comment]
I found probably the root cause for the weird values. This seems to be the issue, a new firmware
![grafik](https://user-images.githubusercontent.com/13933431/141520752-ee54fd24-8ea4-4223-8d58-6ec44c12e895.png)

But it is not helping with the issue

**Comment by splatch** [comment]
I can confirm that I have issues with such equipment starting from October 24th/25th.

**Comment by Homer-Sim** [comment]
Sorry for my impacient question. is this solved now? Also in a 2.5.x binding?

**Comment by DollC** [comment]
I think it is not fixed. I tried the latest available snapshot - it doesn't works.
Can somebody help us?
