### ISSUE TITLE
[shelly] Shelly actions very slow (delayed reception in openHAB)

### ISSUE THREAD

**Issue by Patschifig2021** [openhab/openhab-addons#13395]
## Expected Behavior
House Electric switch equipped with shelly devices feeds/pushes status cange to openHAB for instantaneously. This has worked perfectly fine from openHAB version 1.X to version 3.2.0. However with update to 3.3.0 causes severy troubles.

## Current Behavior
I have been using my set-up with openHAB successfully for several years. Unfortunately after updating to openHAB / openhabian 3.3.0 I encounter serious issues with my Shelly’s (Shelly Binding). I use different shelly’s e.g. 1, 1PM, 2.5 etc. to trigger actions in other bindings which used to work more or less in “real time” ever since. However after updating to openHAB 3.3.0 this works with a huge time delay and the state of the Shelly’s is only changed in openHAB (according the log) when the Shelly is polled by the “heartbeat”, so with a delay of up to 30 seconds. When I restart the raspberry pi 4 it works again fine for a few minutes but then the behaviour is back as described above. 

I de-installed ALL Bindings and than installed one by one including the shelly binding. But this did not help.

In the German openHAB Facebook group, other user have reported the same issue. They downgraded from Version 3.3.0. to Version 3.2.0 and it worked all again fine.

## Possible Solution
- fix the binding / process etc. 
- short time solution: restart/reboot Raspberry pi 4, it then works fine for LESS than 5 minutes
- Downgrading back to Version 3.2.0

## Steps to Reproduce (for Bugs)
https://community.openhab.org/t/shelly-actions-very-slow/138757

## Context
Switching the status of the Shelly triggers actions in other related systems (e.g. switches on Ikea Tradfri bulbs (via Tradfri Gateway) or Philips HUI.

## Your Environment
opeHAB 3.3.0 stable
Bindings: Astro, openweather, Tradfri, Shelly, Sonos, system binding
Operating System and version: openhabian 3.3.0 on Rasberry pi 4 (4GB)

**Comment by markus7017** [comment]
has been fixed in PR #13520

**Comment by Patschifig2021** [comment]
I have updated to the latest stable version 3.3.0 and also re-installed the Shelly Binding. The behaviour is still the same. All works fine for a few minutes, thereafter the commands/actions from the shelly's only "arrive" in Openhab with a significant time delay (ca. 20 to 30 seconds). Like this Openhab and the Shelly Binding is useless for me. I hope this will be fixed with version 3.4.0 latest. Thank you very much.Am 14.11.22, 23:24 schrieb Markus Michels ***@***.***>:

   
  has been fixed in PR #13520
