### ISSUE TITLE
[ipcamera] Discovery crashes immediately

### ISSUE THREAD

**Issue by mpeter50** [openhab/openhab-addons#14500]
## Expected Behavior

The discovery process finds IP cameras on my network.
When starting a manual discovery (with the Scan button), the progress bar on the `/settings/things/add/ipcamera` page gets filled up.

## Current Behavior

The discovery process does not find any IP cameras on my network.
When starting a manual discovery (with the Scan button), the progress bar on the `/settings/things/add/ipcamera` page disappears in a split second.

I have uploaded logs [here](https://gist.github.com/mpeter50/a17ccf9b8f4a99b51e01af871a4856fe), with default log levels plus TRACE level for `org.jupnp` and `org.openhab.binding.ipcamera`.

The openHAB instance does not have special configuration, it was just installed, and the first action on it being done was adding this binding.

There are several other people on the openHAB forum who have this issue, the earliest report I have found being from February of 2021, but so far no solution has been reported: https://community.openhab.org/t/ipcamera-discovery-error/116790

## Steps to Reproduce (for Bugs)

1. Install openHAB in a docker container according to the first compose file example under "Running from compose-file.yml" [here](https://hub.docker.com/r/openhab/openhab/)
2. Open the web interface
3. Install the binding-ipcamera binding
4. Start a scan manually

## Context

I am trying to automatically discover my ONVIF compatible IP cameras.

## Your Environment

* Version used:
  * openHAB container image: openhab/openhab:3.4.2
  * binding-ipcamera version: 3.4.2 
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
  * Desktop
  * openSUSE Leap 15.4 as Docker host
  * Docker version: 20.10.17-ce, build a89b84221c85

**Comment by Skinah** [comment]
I have seen the below error before and I believe it occurs because 1 scan has not fully finished before the 2nd scan is triggered. I did a restart and it was fixed.

```
2023-02-25 13:12:42.692 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot trigger scan for thing types '[ipcamera:generic, ipcamera:dahua, ipcamera:instar, ipcamera:amcrest, ipcamera:hikvision, ipcamera:onvif, ipcamera:foscam, ipcamera:doorbird]' on 'IpCameraDiscoveryService'!
io.netty.channel.ChannelPipelineException: org.openhab.binding.ipcamera.internal.onvif.OnvifDiscovery$2 is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:600) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:202) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370) ~[?:?]
	at io.netty.bootstrap.Bootstrap.init(Bootstrap.java:262) ~[?:?]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:311) ~[?:?]
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:272) ~[?:?]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:268) ~[?:?]
	at org.openhab.binding.ipcamera.internal.onvif.OnvifDiscovery.discoverCameras(OnvifDiscovery.java:220) ~[?:?]
```

I would need to look at this to see what is involved if anything to make the Netty handler be able to be tagged @Sharable. Either stop having multiple scans at the same time, or make it possible to do parallel scans.

**Comment by Skinah** [comment]
Have you setup the network in the openhab network settings page? You need to select which network card openhab is to use and since your in a docker container, you will need to allow the binding to access the network that is selected in openhabs global setup/settings pages. Openhab did do a background scan at one point, so this may be the first scan is not triggered by you and is failing due to docker security settings, or a missing setup of the default network to use. Hopefully this helps you to find a solution whilst waiting for the code to change.

**Comment by mpeter50** [comment]
Yes, I think I did, but I cannot check it right now; the machine I was trying out OpenHAB ran out of storage space, and I had to shut it down.. still dont have much of an idea how will I find some space :/
If you mean the Primary Address setting, then yes.

I don't exactly remember now, but you made me remember [this another issue](https://community.openhab.org/t/upnp-based-discovery-does-not-work-on-host-networked-docker-container/144360) I had with discovery. This might be related in some way, though _I think_ the workaround to that one did not fix this problem.

**Comment by Skinah** [comment]
I think it is probably related and the root cause is docker blocking network traffic. Docker adds complexity that a openhabian setup does not have so it is easier to trial with that setup if you have a spare pi.

From memory the binding regardless of what is set as the primary address will broadcast the discovery out to all networks that is seen. I will look at changing it so it only sends on the selected address. Are you going to continue testing or should I close this issue when I make this proposed change?

**Comment by mpeter50** [comment]
> if you have a spare pi

I only have one, and it does local DNS for everything and such

> Are you going to continue testing or should I close this issue when I make this proposed change?

I'll continue, but probably not this week, or maybe only the second part of it

**Comment by Skinah** [comment]
I have made the change and added some logging to the binding, I will create the PR soon and mark it to close this Issue, if it's not solved just reopen this issue and post some of the extra log info.
