### ISSUE TITLE
[mqtt][homeassistant] Light misses channels

### ISSUE THREAD

**Issue by enboig** [openhab/openhab-addons#14856]
I am using zigbee2mqtt and my light misses switch channel.

```json
{
    "availability": [
        {
            "topic": "zigbee2mqtt/bridge/state"
        }
    ],
    "brightness": true,
    "brightness_scale": 254,
    "command_topic": "zigbee2mqtt/encimeraCuina/set",
    "device": {
        "identifiers": [
            "zigbee2mqtt_0x0c4314fffe0f8ab6"
        ],
        "manufacturer": "IKEA",
        "model": "TRADFRI driver for wireless control (30 watt) (ICPSHC24-30EU-IL-1)",
        "name": "encimeraCuina",
        "sw_version": "2.3.086"
    },
    "effect": true,
    "effect_list": [
        "blink",
        "breathe",
        "okay",
        "channel_change",
        "finish_effect",
        "stop_effect"
    ],
    "json_attributes_topic": "zigbee2mqtt/encimeraCuina",
    "name": "encimeraCuina",
    "schema": "json",
    "state_topic": "zigbee2mqtt/encimeraCuina",
    "unique_id": "0x0c4314fffe0f8ab6_light_zigbee2mqtt"
}
```

The automatic device is:
```
UID: mqtt:homeassistant_zigbee2mqtt_5F0x0c4314fffe0f8ab6:mqtt-broker:encimeraCuina
label: encimeraCuina
thingTypeUID: mqtt:homeassistant_zigbee2mqtt_5F0x0c4314fffe0f8ab6
configuration:
  topics:
    - sensor/0x0c4314fffe0f8ab6/update_state
    - sensor/0x0c4314fffe0f8ab6/power_on_behavior
    - device_automation/0x0c4314fffe0f8ab6/action_on
    - binary_sensor/0x0c4314fffe0f8ab6/update_available
    - select/0x0c4314fffe0f8ab6/power_on_behavior
    - update/0x0c4314fffe0f8ab6/update
    - sensor/0x0c4314fffe0f8ab6/linkquality
    - device_automation/0x0c4314fffe0f8ab6/action_off
    - light/0x0c4314fffe0f8ab6/light
    - select/0x0c4314fffe0f8ab6/effect
  basetopic: homeassistant
bridgeUID: mqtt:broker:mqtt-broker
```
But I don't get any switch for the light.

![Screenshot_20230420_145237](https://user-images.githubusercontent.com/1155203/233372887-f69e8a58-7d1a-4667-8949-8b2aa40aafcf.png)

After reading the documentation, I don't get why it don't work, it uses "ON"/"OFF" for state.

https://www.zigbee2mqtt.io/devices/ICPSHC24-30EU-IL-1.html

## Your Environment
* Version used: openHAB 3.3.0
* Operating System and version: Ubuntu 22.04

**Comment by enboig** [comment]
I upgraded openhab to 3.4 with the same result.

**Comment by enboig** [comment]
The problem continues after upgrading to openhab 4.0.3:

MQTT Config Topic:
```
select/0xa4c138b143374061/backlight_mode
select/0xa4c138b143374061/power_on_behavior
sensor/0xa4c138b143374061/backlight_mode
sensor/0xa4c138b143374061/linkquality
sensor/0xa4c138b143374061/power_on_behavior
switch/0xa4c138b143374061/switch
```

Code:
```
UID: mqtt:homeassistant_zigbee2mqtt_5F0xa4c138b143374061:mqtt-broker:interruptorCuina
label: interruptorCuina
thingTypeUID: mqtt:homeassistant_zigbee2mqtt_5F0xa4c138b143374061
configuration:
  topics:
    - select/0xa4c138b143374061/backlight_mode
    - select/0xa4c138b143374061/power_on_behavior
    - sensor/0xa4c138b143374061/backlight_mode
    - sensor/0xa4c138b143374061/linkquality
    - sensor/0xa4c138b143374061/power_on_behavior
    - switch/0xa4c138b143374061/switch
  basetopic: homeassistant
bridgeUID: mqtt:broker:mqtt-broker
```

But there is no switch channel, only a "Backlight mode"

**Comment by portboy** [comment]
I can confirm this issue.
The autodiscover of things works, but it won't add all discoverd topics to channels.
Without this, the whole "homeassistant" component is useless.
The MQTT Broker works without issues. 

It only appears in combination with autodiscover “HomeAssistant MQTT Components”.
Manually configured mqtt things are working as expected and rock solid.

![image](https://github.com/openhab/openhab-addons/assets/11173760/6750c6a2-ae4d-405c-ade2-f4d50ecefcbf)
![image](https://github.com/openhab/openhab-addons/assets/11173760/536bc793-79a4-4e9b-8c47-dfd6104e070e)

The MQTT Broker works without issues. 
It only appears in combination with autodiscover “HomeAssistant MQTT Components”.
Manually configured mqtt things are working as expected and rock solid.

**Comment by pingvvino** [comment]
It would be great to have a possibility to modify the channels directly from UI. Having that feature would allow to easily bypass the issue and give also other benefits.

**Comment by enboig** [comment]
I have made some discoveries.

I made a script to get all config messages to configure them manually in openhab, and the discovered channels are the first ones in the list; then another devices come in, and items below are ignored.

I am discovering `0x0c4314fffe0f8ab6`
```
{
    "homeassistant/sensor/0x00158d000233f8ae/temperature/config": { //DIFFERENT DEVICE
//...
    "homeassistant/sensor/0x0c4314fffe0f8ab6/power_on_behavior/config": { //ADDED
    "homeassistant/sensor/0x0c4314fffe0f8ab6/linkquality/config": { //ADDED
    "homeassistant/sensor/0x0c4314fffe0f8ab6/update_state/config": { //ADDED
    "homeassistant/binary_sensor/0x00158d000201358f/occupancy/config": { //DIFFERENT DEVICE
//...
    "homeassistant/binary_sensor/0x0c4314fffe0f8ab6/update_available/config": { //CHANNEL IGNORED
    "homeassistant/switch/0x00158d0002a6de0e/switch_left/config": { //DIFFERENT DEVICE
//...
    "homeassistant/device_automation/0x0c4314fffe0f8ab6/action_on/config": { //CHANNEL IGNORED
//...
```

So my guesses are:
- Discovery loop stops when new device come in.
- Some device config breaks the loop (maybe broken json config?)

And I don't know if it may be related, but my `zigbee2mqtt/bridge/info` message appear truncated at 20.000 chars, so json is invalid. I checked with MQTT Explorer, but it don't appear to be a program limit.

**Comment by melvinisken** [comment]
I can confirm this bug on OH 3.4.5. I have two IKEA LEDs and one remote control and all of them are discovered properly but either no channels or an arbitrary number of channels is recognized.

**Comment by enboig** [comment]
It is solved in 4.1; it was a problem with null channel group.

**Comment by melvinisken** [comment]
I upgraded to OH 4.1.0 because I wanted to get rid of this error, but it still persists. The devices get auto-discovered from zigbee2mqtt, but only a few of the available channels are recognized.

**Comment by enboig** [comment]
Could you enable debug log to check? you should enter the console (I use docker, so it was `ssh -p 8101 openhab@localhost`):
```
openhab> log:set DEBUG org.openhab.binding.mqtt.homeassistant
```
open your logs:
```
tail -f userdata/logs/openhab.log
```
and add again, looking for errors.

**Comment by pubFbx** [comment]
Hello, have you found a solution to this problem, which is still present and concerns other devices (humidity sensor TS0601_soil_3, bulb HG06492C/HG08130C/HG09154C or CK-BL702-AL-0). I've been desperately looking for a solution for over a year. Thank you in advance for your help

**Comment by lsiepel** [comment]
> Hello, have you found a solution to this problem, which is still present and concerns other devices (humidity sensor TS0601_soil_3, bulb HG06492C/HG08130C/HG09154C or CK-BL702-AL-0). I've been desperately looking for a solution for over a year. Thank you in advance for your help

Better to create a new issue as this is closed. Please verify with 4.3.0 milestone 4 as last weeks many fixes and enhancements have been added to this binding.

**Comment by melvinisken** [comment]
> Hello, have you found a solution to this problem, which is still present and concerns other devices

In my case, the solution was to move to Homeassistant finally. This issue was not the only reason but the sum of bugs I had to fight with in OH. I always liked OH and also miss some minor things in HA that I had in OH, but I do not regret the move. HA feels more complete and much more solid.

**Comment by pubFbx** [comment]
HA does seem to be more efficient for integrating new devices. I've installed a HA docker which I often use successfully to test hardware when I can't manage it with OH. Having invested a lot in OH, I'm reluctant to change and I'm still giving it a chance. What's more, I've chosen to use Zigbee2mqtt and not the OH mqtt binding in the event of a switch to HA. Thanks for this testimonial
