### ISSUE TITLE
[tesla] Some channels are broken

### ISSUE THREAD

**Issue by kojid0** [openhab/openhab-addons#14967]
Channels _eventstamp_ and _shiftstate_ are not being updated anymore after the [recent API adjustment](https://github.com/openhab/openhab-addons/pull/14924).
Confirmed by a couple of users (see [comments](https://github.com/openhab/openhab-addons/issues/14894))

## Expected Behavior
_eventstamp_ and _shiftstate_ are being updated, just like other channels

## Current Behavior
_eventstamp_ and _shiftstate_ are note being updated.

## Your Environment

* Version used: openHAB 3.3.0 with [tesla binding 3.4.4-SNAPSHOT from PR](https://github.com/openhab/openhab-addons/pull/14924)

**Comment by billfor** [comment]
I pushed this to 3.4 since I haven't been doing anything with 4.0. 
I could not repro drive/shift state not changing.

**Comment by phuongpham** [comment]
Some progress for OH 4.X?
I'm current on OH 4.0.3 and see the eventstamp still get wrong date&time.

**Comment by billfor** [comment]
The fix will only work for 4.1 unless you import the higher versions of libraries. If you want something to drop in your 4.0.3 addon folder you can download https://github.com/billfor/openhab2-addons/blob/teslatimefix_403/bundles/org.openhab.binding.tesla/target/org.openhab.binding.tesla-4.1.0-SNAPSHOT.jar

or pull that branch and build it.  The pom.xml shows the libraries that have to fix set to lower versions to work with 4.0.3 runtime.

**Comment by phuongpham** [comment]
> The fix will only work for 4.1 unless you import the higher versions of libraries to 4.0.3. If you want something to drop in your 4.0.3 addon folder you can download https://github.com/billfor/openhab2-addons/blob/teslatimefix_403/bundles/org.openhab.binding.tesla/target/org.openhab.binding.tesla-4.1.0-SNAPSHOT.jar
> 
> or pull that branch and build it. The pom.xml shows the libraries that have to fix set to lower versions to work with 4.0.3 runtime.

Ok great! I didn't know that the latest snapshot also support 4.0.3.
Tried to update to the jar file you provided. 
But getting follow error:

20:13:36.780 [ERROR] [Events.Framework                     ] - FrameworkEvent ERROR
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
        at io.micrometer.core.instrument.ImmutableTag.<init>(ImmutableTag.java:35) ~[?:?]
        at io.micrometer.core.instrument.Tag.of(Tag.java:29) ~[?:?]
        at org.openhab.core.io.monitor.internal.metrics.BundleStateMetric.createOrUpdateMetricForBundleState(BundleStateMetric.java:78) ~[?:?]
        at org.openhab.core.io.monitor.internal.metrics.BundleStateMetric.bundleChanged(BundleStateMetric.java:74) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:949) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi-3.18.0.jar:?]

**Comment by billfor** [comment]
I just downloaded from the link I provided and it works on my 4.0.3.  I don't think I did anything special with it. That pom.xml that builds it should restrict the libraries. It says 4.1 snapshot but that version is compiled with a pom.xml to restrict the versions to what is available in 4.0.3. It's always possible that I manually imported something else into 4.0.3 but I don't think I did.

**Comment by phuongpham** [comment]
> https://github.com/billfor/openhab2-addons/blob/teslatimefix_403/bundles/org.openhab.binding.tesla/target/org.openhab.binding.tesla-4.1.0-SNAPSHOT.jar

Thanks for your feedback.
The OH still not working as expected. In karaf and bundle:list command I get this

311 │ Active │  80 │                        │ mvn:org.openhab.addons.bundles/org.openhab.binding.tesla/4.0.3


Before update I see this in karaf:

311 │ Active │  80 │ 4.0.3                  │ openHAB Add-ons :: Bundles :: Tesla Binding

**Comment by billfor** [comment]
Yeah on  mine it runs fine. It might be some difference in the runtime configurations.

`304 │ Active  │  80 │ 4.1.0.202310141906     │ org.openhab.binding.tesla`

**Comment by phuongpham** [comment]
> Yeah on mine it runs fine. It might be some difference in the runtime configurations.
> 
> `304 │ Active │ 80 │ 4.1.0.202310141906 │ org.openhab.binding.tesla`

What version of OH are you running on?
