### ISSUE TITLE
[shelly] Wall Display authentication does not work

### ISSUE THREAD

**Issue by mmatuska** [openhab/openhab-addons#16341]
## Expected Behavior
OpenHAB should connect to Shelly Wall Display when authentication is enabled

## Current Behavior
OpenHAB receives an error and does not connect when authentication is enabled

## Steps to Reproduce (for Bugs)
1. Configure password authentication on Shelly Wall Display
2. Configure password for OpenHAB thing

## Your Environment
* OpenHAB 4.1.1

**Comment by mmatuska** [comment]
@markus7017 FYI

**Comment by markus7017** [comment]
solved in between

**Comment by mmatuska** [comment]
Not solved, I am still getting:
Unable to connect to device - java.lang.IllegalArgumentException: Unsupported Auth type/algorithm requested by device(class java.lang.IllegalArgumentException)

**Comment by lsiepel** [comment]
Could you create a new issue, with a debug log and as much details as possible. If you provide those, i'm convinced Markus knows how to fix it.

**Comment by mmatuska** [comment]
I have contacted Alterco, looks like the problem is on their side. They promised a fix with the next firmware.
