### ISSUE TITLE
[shelly] "duplicate id" warnings in device logs

### ISSUE THREAD

**Issue by alaub81** [openhab/openhab-addons#19223]
## Expected Behavior
no warnings in the devices debug logs.

## Current Behavior
in the shelly device debug log there are warnings like this one:

`shellypmminig3-54320459a06c 236900 4243235.127 1 1|shos_rpc_inst.c:374     0x3fcce154: duplicate id 'openhab-192.168.1.20'`

## Possible Solution
I have no clue, but can support with more informations or testing.

## Steps to Reproduce (for Bugs)
setup openHAB 5.0.1 with latest shelly DEV binding. [Setup a syslog server ](https://www.laub-home.de/wiki/Syslog-Server_Docker_Stack_mit_Webinterface_für_Log-Analyse) and configure the shelly devices to log to the syslog. check the syslog messages. Or have a look at the devices debug log.

## Your Environment
* Raspbian OS with docker compose setup of openHAB
* openHAB 5.0.1
* shelly binding DEV Build 5.1.0

**Comment by jlaur** [comment]
@alaub81 - can you please reproduce the issue with the official 5.0.1 binding, i.e. not the DEV binding?

**Comment by alaub81** [comment]
With the official 5.0.1 it is the same behavior. This Warning exists since at least openHAB 4.3.x. There are also older discussions on this issue.

**Comment by markus7017** [comment]
I'm aware of this issue and are planning a fix. I'll let you know if it's ready to test

**Comment by markus7017** [comment]
@alaub81 Could you please re-test with the current DEV build. I know I fixed it, but maybe the change got lost.

**Comment by alaub81** [comment]
@markus7017 I still see the warnings with dev build 5.1.0.202512261525 and openHAB version 5.1.0

**Comment by markus7017** [comment]
@alaub81 Please try this build:
https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-5.2.0-SNAPSHOT-cachemdns.jar?raw=true

Do not user for production, still not done. It has issues with BLU support reading temperatures.

**Comment by alaub81** [comment]
I did a test with new instance of openHAB 5.1.1 only with the shelly Binding (the build above) and one Shelly Plus Plug S (gen2) and I can't see the message after running the setup for about 4h. Looks good.

I can see a new message:

```txt
Jan 28 12:21:54 shelly-sd-test shellyplusplugs-b0b21c19a7c8 497 13295.107 2 0|shos_http_server.cp:266 192.168.50.20: No handler for '/settings'
Jan 28 12:21:54 shelly-sd-test shellyplusplugs-b0b21c19a7c8 498 13295.123 2 0|shos_http_server.cp:266 192.168.50.20: No handler for '/settings'
```

I can see this also on my production side with dev build 5.2.0.202601101913.

So I think the duplicate warnings are fixed. Will have a look for them in the next 24h

**Comment by markus7017** [comment]
Now I need to work on PRs to bring it to the main branch

**Comment by alaub81** [comment]
I checked the logs again after running the build for about 24h. I Can't see any duplicate id warnings. And also the logs are looking cleaner, then before, just wanted to leave that here, but it is not really related to this Ticket:

```txt
Jan 29 08:09:15 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3038 84629.845 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1054@ohshelly-999023f8cc-1054] via HTTP_in POST 192.168.50.20:47216
Jan 29 08:09:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3039 84672.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769670600,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:10:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3040 84690.031 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1055@ohshelly-999023f8cc-1055] via HTTP_in POST 192.168.50.20:47720
Jan 29 08:10:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3041 84732.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769670660,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:11:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3042 84750.221 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1056@ohshelly-999023f8cc-1056] via HTTP_in POST 192.168.50.20:58958
Jan 29 08:11:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3043 84792.937 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769670720,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:12:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3044 84810.412 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1057@ohshelly-999023f8cc-1057] via HTTP_in POST 192.168.50.20:49288
Jan 29 08:12:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3045 84852.937 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769670780,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:13:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3046 84870.607 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1058@ohshelly-999023f8cc-1058] via HTTP_in POST 192.168.50.20:56154
Jan 29 08:13:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3047 84912.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769670840,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:14:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3048 84930.793 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1059@ohshelly-999023f8cc-1059] via HTTP_in POST 192.168.50.20:40458
Jan 29 08:14:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3049 84972.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769670900,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:15:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3050 84990.988 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1060@ohshelly-999023f8cc-1060] via HTTP_in POST 192.168.50.20:41700
Jan 29 08:15:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3051 85032.937 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769670960,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:16:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3052 85051.178 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1061@ohshelly-999023f8cc-1061] via HTTP_in POST 192.168.50.20:35528
Jan 29 08:16:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3053 85092.937 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671020,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:17:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3054 85111.365 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1062@ohshelly-999023f8cc-1062] via HTTP_in POST 192.168.50.20:57580
Jan 29 08:17:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3055 85152.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671080,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:18:16 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3056 85171.564 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1063@ohshelly-999023f8cc-1063] via HTTP_in POST 192.168.50.20:33812
Jan 29 08:18:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3057 85212.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671140,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:19:17 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3058 85231.747 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1064@ohshelly-999023f8cc-1064] via HTTP_in POST 192.168.50.20:57282
Jan 29 08:19:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3059 85272.937 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671200,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:20:17 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3060 85291.936 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1065@ohshelly-999023f8cc-1065] via HTTP_in POST 192.168.50.20:42480
Jan 29 08:20:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3061 85332.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671260,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:21:17 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3062 85352.127 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1066@ohshelly-999023f8cc-1066] via HTTP_in POST 192.168.50.20:47436
Jan 29 08:21:58 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3063 85392.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671320,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:22:17 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3064 85412.320 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1067@ohshelly-999023f8cc-1067] via HTTP_in POST 192.168.50.20:41294
Jan 29 08:22:57 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3065 85452.937 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671380,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:23:17 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3066 85472.514 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1068@ohshelly-999023f8cc-1068] via HTTP_in POST 192.168.50.20:41296
Jan 29 08:23:57 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3067 85512.937 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671440,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}
Jan 29 08:24:17 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3068 85532.716 2 2|shos_rpc_inst.c:243     Shelly.GetStatus [1069@ohshelly-999023f8cc-1069] via HTTP_in POST 192.168.50.20:39720
Jan 29 08:24:57 shelly-sd-test shellyplusplugs-b0b21c19a7c8 3069 85572.938 2 2|shelly_notification:164 Status change of switch:0: {"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1769671500,"total":0.000},"apower":0.0,"current":0.000,"voltage":0.0}

```

Big thanks to @markus7017 !!!
