### ISSUE TITLE
[homekit] Make thermostat temperature limits configurable

### ISSUE THREAD

**Issue by weakfl** [openhab/openhab-addons#3400]
<a alt="bounty" href="https://www.bountysource.com/issues/56349501"><img src="https://api.bountysource.com/badge/issue?issue_id=56349501"></a>

It would be great if temperature limits for thermostats could be configured independently.
I know there are already `minimumTemperature` and `maximumTemperature` settings, but they have an impact on all temperature items (like outdoor temperature sensors).

To get practical limits for thermostat temperature sliders separate settings would be required.

/cc @beowulfe

**Comment by weakfl** [comment]
[Bounty available](https://www.bountysource.com/issues/56349501-feature-homekit-make-thermostat-temperature-limits-configurable)

@wborn Could you please label accordingly, thanks.

**Comment by spacesuitdiver** [comment]
This duplicates #1648 :\

**Comment by martinvw** [comment]
And this PR is also related, but imho not really a great solution: https://github.com/openhab/openhab2-addons/pull/2861

**Comment by weakfl** [comment]
> This duplicates #1648 :\

@spacesuitdiver It does not. As I've written `minimumTemperature` and `maximumTemperature` affect **all** temperature related items. I'm talking about thermostat specific settings.

Also #1648 has probably already been fixed with [PR 5018](https://github.com/eclipse/smarthome/pull/5018)

**Comment by weakfl** [comment]
> And this PR is also related, but imho not really a great solution: #2861 

Agree. Imho #2861 should not be merged. All it does is changing the default values, which are already configurable anyway.

**Comment by ccutrer** [comment]
This is trivial (and already planned) once all of @timcharper and my commits are merged upstream. Locally I’m already doing something similar for my Fan and SecuritySystem implementations. Basically we’ll use item metadata to configure complex accessories, and for per-accessory config.

**Comment by J-N-K** [comment]
@ccutrer is this fixed in master?

**Comment by ccutrer** [comment]
No, not yet

**Comment by weakfl** [comment]
Heating season is approaching, so I've increased the bounty. It's still not much, but others are welcome to add to the cause 😉
