### ISSUE TITLE
[mqtt] Handler was already disposed

### ISSUE THREAD

**Issue by tdeckers** [openhab/openhab-addons#4835]
I have a boolean value coming in through MQTT and I have a rule that watches the value to sends a notification when the value changes to true.

Item definition:
```
$ cat ./items/mqtt.items 
Switch mq_gate 		"Gate"
```
I've used homie auto-discovery and the UI to connect the thing to this item.

## Expected Behavior
No errors/warnings in the log

## Current Behavior
Each time the value is received I get following line in the log (4x the same line):
```
2019-02-08 15:54:59.647 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomieThingHandler of thing mqtt:homie300:embedded-mqtt-broker:passage_sensor1 tried triggering channel passage#blocked although the handler was already disposed.
2019-02-08 15:54:59.648 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomieThingHandler of thing mqtt:homie300:embedded-mqtt-broker:passage_sensor1 tried triggering channel passage#blocked although the handler was already disposed.
2019-02-08 15:54:59.677 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomieThingHandler of thing mqtt:homie300:embedded-mqtt-broker:passage_sensor1 tried triggering channel passage#blocked although the handler was already disposed.
2019-02-08 15:54:59.678 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomieThingHandler of thing mqtt:homie300:embedded-mqtt-broker:passage_sensor1 tried triggering channel passage#blocked although the handler was already disposed.
```

## Possible Solution
Not sure... have seen mentions to a similar message for other bindings, but first glance through the code doesn't show anything obvious.

## Steps to Reproduce (for Bugs)
1. Configure MQTT device
2. Trigger boolean value to change
3. See error messages in the log

## Your Environment
* Version used: 2.4
* Environment name and version: running official docker container for 2.4.0
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): See previous comment.

**Comment by davidgraeff** [comment]
Unfortunately 2.4 is quite old already for the MQTT binding development. I think this has been fixed already. Can you verify if this is still a problem on an OH 2.5M1?

**Comment by tdeckers** [comment]
Ok, I'll try to find some time. Would I be able to use the 2.5M1 addon  with my 2.4.0 installation? Or do I need to use an entire 2.5M1 deployment?

**Comment by davidgraeff** [comment]
Yes, you can uninstall the distribution addons and use the mqtt binding jar file. But there where also some fixes in the core regarding rule actions in general. If you do not use the mqtt action you are not affected though.

**Comment by tdeckers** [comment]
Is there a jar file I can download somewhere?  The openhab2-addons repo from git (branch 2.5.0.M1) doesn't build successfully.

**Comment by J-N-K** [comment]
Should be fixed with latest changes to the subscription logic

**Comment by Jolly-Roger82** [comment]
unfortunately I still have this issue on 2.5M3

`2019-10-02 09:10:59.832 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler GenericMQTTThingHandler of thing mqtt:topic:sonoff_1 tried updating channel power although the handler was already disposed.`

**Comment by xdanik** [comment]
Same issue here.
I my case it starts to appear after I change the .thing file.
Restarting openhab fixes the issue.
So probably a problem with un-uloading the thing before re-loading a config file?

**Comment by J-N-K** [comment]
There was a bug fixed with reloading things from textual configuration last week. Maybe that helps.

**Comment by rgabo74** [comment]
I am experiencing the same behavior on 2.5M5. The issues comes up when I make a mistake in one of the .things file and the things not loaded. Even if I fix the error in the file, the warning keep on flooding the logs until I restart the service.
