### ISSUE TITLE
[mqtt] RollerShutters doesn't work

### ISSUE THREAD

**Issue by fab33** [openhab/openhab-addons#4890]
With OH 2.5M1 (deb repos)
Thing file : 
```
Bridge mqtt:broker:mosquitto [ host="mqtt.lan", secure=false, username="username", password="pass" ]
{
    Thing topic objets {
	Type rollershutter : Test_Volet [ stateTopic="test/volet", commandTopic="test/volet/command" ] 
    }
}

```
item file : 
```
Rollershutter Test_Volet "Volet Test" { channel="mqtt:topic:mosquitto:objets:Test_Volet" }
```
When I want to UP/DOWN/STOP : 
```
21:33:28.436 [ERROR] [rnal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.eclipse.smarthome.binding.mqtt.generic.internal.handler.GenericThingHandler@2e6629d4': Cannot call update() with custom stop/move/up/down
java.lang.IllegalStateException: Cannot call update() with custom stop/move/up/down
        at org.eclipse.smarthome.binding.mqtt.generic.internal.values.RollershutterValue.update(RollershutterValue.java:62) ~[?:?]
        at org.eclipse.smarthome.binding.mqtt.generic.internal.generic.ChannelState.publishValue(ChannelState.java:321) ~[?:?]
        at org.eclipse.smarthome.binding.mqtt.generic.internal.handler.AbstractMQTTThingHandler.handleCommand(AbstractMQTTThingHandler.java:123) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.11.0.oh250M1]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [102:org.eclipse.smarthome.core:0.11.0.oh250M1]
        at com.sun.proxy.$Proxy220.handleCommand(Unknown Source) [217:org.eclipse.smarthome.binding.mqtt.generic:0.11.0.oh250M1]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [109:org.eclipse.smarthome.core.thing:0.11.0.oh250M1]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [109:org.eclipse.smarthome.core.thing:0.11.0.oh250M1]
        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.11.0.oh250M1]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.11.0.oh250M1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by davidgraeff** [comment]
Hm. I just looked up in the code. That use case is not supported at the moment. Right now you can receive UP,DOWN,STOP from MQTT. But you cannot post UP,DOWN,STOP commands to a rollershutter item, connected to an MQTT channel.

The binding would not know what to send via the MQTT protocol. So I first need to add the configuration options to define what text to send for UP/DOWN/STOP.

**Comment by davidgraeff** [comment]
Fixed in master

**Comment by robot22** [comment]
Hi, 
I've tried to setup a similar installation and for me it's still not working. I'm running Openhab 2.4
Is this only fixed in the 2.5 openhab? I thought that the addon's using the same code?

.things
```
Bridge mqtt:broker:mosquitto [ host="openhab.local",secure=false, username="username", password="password", reconnect_time_ms=10000, clientID="Openhab" ]
{
    Thing mqtt:topic:generic {
        Channels:
        Type rollershutter : SZ_Rollladen "Schlafzimmer Rollladen" [ commandTopic="windows/sz", on="UP", stop="STOP", off="DOWN" ]
    }
}
```
.items
`Rollershutter SZ_Rollladen "Rolladen []" { channel = "mqtt:topic:generic:SZ_Rollladen" }`

**Comment by davidgraeff** [comment]
> Is this only fixed in the (**unreleased**) 2.5 openhab?

yes

**Comment by robot22** [comment]
Sorry for my late reply and thanks for your answer. I've used rules to have a workaround :)
