### ISSUE TITLE
[daikin] Binding generates multiple 'Received command of wrong type' warnings at start

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-addons#6413]
When loading the Daikin AC binding, it generates multiple warnings in the log, like:
```
Received command of wrong type for thing '<daikin thing>' on channel <some channel>
```

This warning is generated because openHAB sends multiple REFRESH commands to the different channels. The binding does not handle RefreshType commands but does generate warnings for each of these commands send to the handler.

Since the binding chooses to not deal with RefreshType commands, I propose to change the warning to a debug message in `InternalThingHandler` and also add the offending command to the message:
```
        logger.debug("Received command '{}' of wrong type for thing '{}' on channel {}", command, thing.getUID().getAsString(),
                channelUID.getId());
```

I'll create a tiny PR for this if we agree.
This way I can also get to know the mechanisms for a PR on openHAB and be prepared for the (Philips Air Purifier) binding I am developing. ;o)

**Comment by psmedley** [comment]
This should be fixed already in the 2.5 code

**Comment by justClouds** [comment]
> This should be fixed already in the 2.5 code

Indeed, snapshot #1754 still shows this behaviour.
I'll create this tiny PR; gives me some practice... ;o)

**Comment by jimtng** [comment]
Can someone check to see whether this is still a problem in the latest version 2.5.3? I believe it has been fixed, so this issue can be closed.

**Comment by crazyelectron-io** [comment]
I have not seen these messages anymore at startup.

**Comment by jimtng** [comment]
@kaikreuzer / @cpmeister sorry for tagging multiple people, not sure who can close this issue. It has been resolved for some time.

**Comment by psmedley** [comment]
Issue resolved.
