### ISSUE TITLE
[kostalinverter][Kostal][Zwave] Zwave binding blocking Kostal setup in paper ui

### ISSUE THREAD

**Issue by leiweke** [openhab/openhab-addons#7090]
Hello Kostal Zwave binding owner,
make a fresh openhabian installation, run upgrade in openhabian menu, setup the basics in paper ui configuration/systems
then installed Kostal Binding.
go to inbox click + select Kostal Inverter Binding then I click KOSTAL PLENTICORE Plus 8.5 (no Battery) a Things pop-up come up and I can put in all details. Thing is added and I can see and select all channels and connect them to items. in Control I see all items with all values. Works great.

then I installed the zwave binding
binding = kostalinverter,zwave

after some minutes zwave binding is installed, check in logs. If I click Control in paper ui -> internal Server Error 500
under Things I see the Kostal inverter but no channels 

as soon I removed zwave binding 
Kostal thing and values show up in paper ui.

I posted here more details/infos
https://community.openhab.org/t/kostal-inverter-binding-interoperable-issue-thinks-not-working-uid-must-have-at-least-2-segments/90267

**Comment by tah78** [comment]
Hi @RS84 could you please have a look at this issue? I saw that you provided a lot of the functionality for this binding, which works great without zwave binding. But I use both bindings and it would be great if someone of the professionals could have a look.

Thanks a lot. Best regards,
Torsten

**Comment by leiweke** [comment]
Hello @tah78 @RS84 any news on this issue? many thanks

**Comment by tah78** [comment]
Nothing new here. I implemented my Kostal Plenticore Plus with battery via Modbus binding. It's a lot of work, but it works in my constellation with Zwave.

<img width="246" alt="Bildschirmfoto 2020-06-22 um 11 24 12" src="https://user-images.githubusercontent.com/45661849/85271954-cb1eec80-b47b-11ea-8553-9d9dd1b8b209.png">

**Comment by leiweke** [comment]
@tah78 great, I would love to know how you did it ;-)

**Comment by tah78** [comment]
@leiweke I think it is a little bit off-topic here. How can I give you some more details? Is it possible to send private messages here or are you registered to openhab forum?

**Comment by leiweke** [comment]
@tah78 yes same username in openhab forum or you email my username @ username de :-)

**Comment by schrej-zz** [comment]
Hi,
does anyone care for this bug?
It would be great to have this issue solved.
Thanks Joerg

**Comment by basse04** [comment]
Hi,
I will have a look. I have redesigned the binding with extensions for Second Generation, but this might be regarded to Kostal binding in common vs Zwave, we will see. I let you know!
BR Basse

**Comment by basse04** [comment]
Hi,
this is so strange. I have seen the fault for the last 4 hours. Then I cut and paste one line during searching for reasons to the problem: 
in src/main/resources/OH-INF/thing/PIKOIQ100.xml / <config-description-ref uri="thing-type:kostalplenticorepikoiq_config"/>
and after that is not possible for me to have the fault visible any more. I have start/stop/start.... a lot of times and everything works.
I can just see Zwave binding configuration running, but I have no Zwave device so I can't go any further, but I can run and confirm the Kostal Inverter 10-20 is working.

I have an ongoing PR with the extensions for PIKO10-20, #8574, do you think I will upload this change to this or is it better to handle it in another way.

BR Basse

**Comment by schrej-zz** [comment]
Hi @basse04,
thanks for digging deeper into this topic.
I would suggest a seperate PR to set it in corellation to the issue.
If there is a compiled version including the change, I am willing to test it for sure.
Joerg

**Comment by basse04** [comment]
Just found another strange thing, 
in src/main/resources/OH-INF/thing/PIKOIQ100.xml / <config-description-ref uri="thing-type:kostalplenticorepikoiq_config"/>
Due to https://www.openhab.org/docs/developer/bindings/binding-xml.html  should it be like <config-description-ref uri="{binding|thing-type|channel-type|any_other}:bindingID:..." />

I have found the very same syntax ( with _ instead of : ) in my binding version too (with PIKO10-20). I must have copied this line ;-)
I can then have the binding start / not start by switching these two signs.
I must earlier have done some mismatch about cut and  paste though I then used the very same text( with _ ), but it seems at least to have lead me in right direction.

Basse

**Comment by basse04** [comment]
Just for the record, you have to change sign in OH-INF / config / SecondGeneration.xml & ThirdGeneration.xml too.

Basse

**Comment by schrej-zz** [comment]
Hi @basse04,
thanks for looking into this.
I don't really get, what you mean.
Seems something is missing in your post above after "should it be like".
Nevertheless, Im confident, that you will add the changes into a PR, and we will see a corrected version in one of the next snapshots.
Thanks Joerg

**Comment by schrej-zz** [comment]
@basse04,
I just opened a separate issue, as from my point of view, the things are way to complex.
I see no need for seperate things for most of the devices.
See #10056 and let's discuss there.
Thanks for maintaining this binding.
Joerg

**Comment by basse04** [comment]
Sorry, my mistake, the missing text is like:
<config-description-ref uri="{binding|thing-type|channel-type|any_other}:bindingID:..." />

Basse

**Comment by basse04** [comment]
Hm, the text somehow disappears?
"    <config-description-ref uri="{binding|thing-type|channel-type|any_other}:bindingID:..." />  "

**Comment by basse04** [comment]
config-description-ref uri="{binding|thing-type|channel-type|any_other}:bindingID:...

**Comment by basse04** [comment]
Hi!
Changes uploaded, and will hopefully solve this issue. I have the binding working in IDE without any faultmessages as before.
I have done changes in parts regarded to Third generation, hope that this is OK even if there is another author for this part .

BR basse

**Comment by schrej-zz** [comment]
Hi @basse04,
great. Is there a JAR somewhere that I can test, or will it be integrated in one of the next OH3 snapshots?
Joerg

**Comment by basse04** [comment]
Hi,
I have just uploaded the version as is also sent for reviewing.
Please try,
https://github.com/basse04/Test

Best Regards Basse

**Comment by schrej-zz** [comment]
Hi,
I tested your binding and it works as expected together with Z-Wave binding.
I do have access to all channels and see all of the the former missing fields, when adding a Kostal thing.
Thanks for your support.
Hope, that it will find its way in one of the upcoming OH 3 snapshots.

Joerg

**Comment by DUSAG0211** [comment]
I am on 3.1 but still get the messages about invalid uid segments once Z-wave abd Kostal binding are installed. Are the changes already included in the release version?

**Comment by chris922** [comment]
I noticed the issue is not yet fixed in 3.1.0 and can't find an opened PR so I just opened one ( https://github.com/openhab/openhab-addons/pull/11002 ) that should fix it.

**Comment by DUSAG0211** [comment]
Thanks. I did bot kbow where I should have started to look. But I also had trouble to get Basse04 package from above installed. OH3 seems to ignore it in the addons folder

**Comment by kaikreuzer** [comment]
Hopefully fixed by #11002.

**Comment by Thorte007** [comment]
Hi Kai, I still have the problem. ZWave is working fine but if I try to add any kostal-plenticore binding, the system is going into a  infinite loop.
