### ISSUE TITLE
Travis openjdk11 is failing

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-addons#8094]
This has been happening for a couple of days now:

`[ERROR] Failed to execute goal org.openhab.tools.sat:sat-plugin:0.9.0:pmd (sat-all) on project org.openhab.binding.insteon: Unable to execute mojo: Execution null of goal org.apache.maven.plugins:maven-pmd-plugin:3.11.0:pmd failed: Couldn't find necessary supporting classes for: Unsupported Tool 'xml' => org.apache.velocity.tools.generic.XmlTool (java.lang.NoClassDefFoundError: org/dom4j/Node) -> [Help 1]`

openjdk8 passes

**Comment by robnielsen** [comment]
@openhab/add-ons-maintainers can this be fixed?

**Comment by kaikreuzer** [comment]
I'd love to see it fixed, but have no idea what change might have caused this now, while it was working before...

**Comment by martinvw** [comment]
It seems that this has been corrected see https://travis-ci.com/github/openhab/openhab-addons

**Comment by robnielsen** [comment]
This is not fixed, it's still failing. See https://travis-ci.com/github/openhab/openhab-addons/builds/178249524. This is from the JDK 11 log file:

```
[WARNING] Could not find file feature file features/karaf/openhab-addons/src/main/feature/feature.xml
[ERROR] Failed to execute goal org.openhab.tools.sat:sat-plugin:0.9.0:pmd (sat-all) on project org.openhab.binding.insteon: Unable to execute mojo: Execution null of goal org.apache.maven.plugins:maven-pmd-plugin:3.11.0:pmd failed: Couldn't find necessary supporting classes for: Unsupported Tool 'xml' => org.apache.velocity.tools.generic.XmlTool (java.lang.NoClassDefFoundError: org/dom4j/Node) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.openhab.binding.insteon
travis_time:end:0a6f515a:start=1596455833035532699,finish=1596455908124463183,duration=75088930484,event=script
```

**Comment by martinvw** [comment]
Thanks for reporting, the build which I was pointing too might only have build a single module, I will look into it.

**Comment by martinvw** [comment]
It seems to be a caching issue, it works fine locally with Java 11 and after clearing the caches we have a green build. 

https://travis-ci.com/github/openhab/openhab-addons/builds/178249524
