### ISSUE TITLE
OH3: build failing (bad format violations in a POM)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#8712]
Is there a way to disable this check ?

````
[INFO] --- spotless-maven-plugin:2.0.3:check (codestyle_check) @ org.openhab.addons.reactor.bundles ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] openHAB Add-ons .................................... SUCCESS [03:12 min]
[INFO] openHAB Add-ons :: BOM ............................. SUCCESS [  0.062 s]
[INFO] openHAB Add-ons :: BOM :: Runtime Index ............ SUCCESS [03:07 min]
[INFO] openHAB Add-ons :: BOM :: Test Index ............... SUCCESS [ 22.930 s]
[INFO] openHAB Add-ons :: BOM :: openHAB Core Index ....... SUCCESS [01:54 min]
[INFO] openHAB Add-ons :: Bundles ......................... FAILURE [ 37.950 s]
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:23 min
[INFO] Finished at: 2020-10-10T13:21:45+02:00
[INFO] Final Memory: 135M/512M
[INFO] ------------------------------------------------------------------------
[INFO] Static code analysis summary report is available in:
[INFO] file:/D:/dev/openhab2/git/openhab-addons/target/summary_report.html
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.0.3:check (codestyle_check) on project org.openhab.addons.reactor.bundles: The following files had format violations:
[ERROR]     pom.xml
[ERROR]         @@ -1,554 +1,554 @@
[ERROR]         -<?xml version="1.0" encoding="UTF-8" standalone="no"?>\r\n
[ERROR]         -<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\r\n
[ERROR]         -  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">\r\n
[ERROR]         -\r\n
[ERROR]         -  <modelVersion>4.0.0</modelVersion>\r\n
[ERROR]         -\r\n
[ERROR]         -  <parent>\r\n
[ERROR]         -    <groupId>org.openhab.addons</groupId>\r\n
[ERROR]         -    <artifactId>org.openhab.addons.reactor</artifactId>\r\n
[ERROR]         -    <version>3.0.0-SNAPSHOT</version>\r\n
[ERROR]         -  </parent>\r\n
[ERROR]         -\r\n
[ERROR]         -  <groupId>org.openhab.addons.bundles</groupId>\r\n
[ERROR]         -  <artifactId>org.openhab.addons.reactor.bundles</artifactId>\r\n
[ERROR]         -  <packaging>pom</packaging>\r\n
[ERROR]         -\r\n
[ERROR]         -  <name>openHAB Add-ons :: Bundles</name>\r\n
[ERROR]         -\r\n
[ERROR]         -  <modules>\r\n
[ERROR]         -    <!-- io -->\r\n
[ERROR]         -    <module>org.openhab.io.homekit</module>\r\n
[ERROR]         -    <module>org.openhab.io.hueemulation</module>\r\n
[ERROR]         -    <module>org.openhab.io.imperihome</module>\r\n
[ERROR]         -    <module>org.openhab.io.neeo</module>\r\n
[ERROR]         -    <module>org.openhab.io.openhabcloud</module>\r\n
[ERROR]         -    <module>org.openhab.io.transport.modbus</module>\r\n
[ERROR]         -    <!-- transformations -->\r\n
[ERROR]         -    <module>org.openhab.transform.bin2json</module>\r\n
[ERROR]         -    <module>org.openhab.transform.exec</module>\r\n
[ERROR]         -    <module>org.openhab.transform.javascript</module>\r\n
[ERROR]         -    <module>org.openhab.transform.jinja</module>\r\n
[ERROR]         -    <module>org.openhab.transform.jsonpath</module>\r\n
[ERROR]         -    <module>org.openhab.transform.map</module>\r\n
[ERROR]         -    <module>org.openhab.transform.regex</module>\r\n
[ERROR]         -    <module>org.openhab.transform.scale</module>\r\n
[ERROR]         -    <module>org.openhab.transform.xpath</module>\r\n
[ERROR]         -    <module>org.openhab.transform.xslt</module>\r\n
[ERROR]         -    <!-- bindings -->\r\n
[ERROR]         -    <module>org.openhab.binding.adorne</module>\r\n
[ERROR]         -    <module>org.openhab.binding.airquality</module>\r\n
[ERROR]         -    <module>org.openhab.binding.airvisualnode</module>\r\n
[ERROR]         -    <module>org.openhab.binding.alarmdecoder</module>\r\n
[ERROR]         -    <module>org.openhab.binding.allplay</module>\r\n
[ERROR]         -    <module>org.openhab.binding.amazondashbutton</module>\r\n
[ERROR]         -    <module>org.openhab.binding.amazonechocontrol</module>\r\n
[ERROR]         -    <module>org.openhab.binding.ambientweather</module>\r\n
[ERROR]         -    <module>org.openhab.binding.astro</module>\r\n
[ERROR]         -    <module>org.openhab.binding.atlona</module>\r\n
[ERROR]     ... (1060 more lines that didn't fit)
[ERROR] Run 'mvn spotless:apply' to fix these violations.
```

Even using `-DskipChecks` does not help avoiding this blocking step.

**Comment by lolodomo** [comment]
I even don't find this project org.openhab.addons.reactor.bundles in the repo.

**Comment by J-N-K** [comment]
I run into that problem sometimes, too. I guess it‘s something with the git line-ending setting.

You can use `-D“spotless.check.skip“=true` to skip the check.

**Comment by lolodomo** [comment]
I got the same error when running `mvn clean install -D“spotless.check.skip“=true`

**Comment by lolodomo** [comment]
Check bypassed if I use the following command: `mvn clean install -Dspotless.check.skip=true` with the ""

**Comment by lolodomo** [comment]
I am on Windows. You say if could be git line-ending setting. Could it be a wrong line encoding of this POM file ?

**Comment by J-N-K** [comment]
My feeling is that it‘s more a spotless bug (could be it doesn‘t detect the correct line-ending).

**Comment by J-N-K** [comment]
Very interestingnit works for you without the "". It‘s not working for me without. Are you using `cmd` („Eingabeaufforderung“ in german, not sure how it is labelled in other languages) or Powershell?

**Comment by lolodomo** [comment]
It was run from a Git Bash windows.

**Comment by lolodomo** [comment]
With spotless checking disabled, the build succeeded.
It takes 1h14'. I have the feeling it takes largely more time than before (OH2) (twice the time ?).

**Comment by lolodomo** [comment]
Here are the bindings that took more than 30s to build:
```
[INFO] openHAB Add-ons :: Bundles :: Adorne Binding ....... SUCCESS [ 45.838 s]
[INFO] openHAB Add-ons :: Bundles :: Chromecast Binding ... SUCCESS [ 56.020 s]
[INFO] openHAB Add-ons :: Bundles :: IO :: Modbus Transport SUCCESS [ 41.393 s]
[INFO] openHAB Add-ons :: Bundles :: Netatmo Binding ...... SUCCESS [ 45.396 s]
[INFO] openHAB Add-ons :: Bundles :: Smartmeter Binding ... SUCCESS [ 55.726 s]
[INFO] openHAB Add-ons :: Bundles :: Tellstick Binding .... SUCCESS [ 36.847 s]
[INFO] openHAB Add-ons :: Bundles :: IO :: Homekit ........ SUCCESS [ 32.935 s]
[INFO] openHAB Add-ons :: Bundles :: IO :: Hue Emulation Service SUCCESS [01:11 min]
[INFO] openHAB Add-ons :: Bundles :: Persistence Service :: DynamoDB SUCCESS [ 50.583 s]
[INFO] openHAB Add-ons :: Bundles :: Persistence Service :: InfluxDB SUCCESS [ 44.463 s]
[INFO] openHAB Add-ons :: Bundles :: Persistence Service :: JDBC SUCCESS [ 44.501 s]
[INFO] openHAB Add-ons :: Bundles :: Persistence Service :: JPA SUCCESS [ 52.672 s]
[INFO] openHAB Add-ons :: Bundles :: Voice :: Mary Text-to-Speech SUCCESS [01:17 min]
[INFO] openHAB Add-ons :: Integration Tests :: Feed Binding Tests SUCCESS [02:46 min]
[INFO] openHAB Add-ons :: Integration Tests :: Nest Binding Tests SUCCESS [ 32.563 s]
[INFO] openHAB Add-ons :: Integration Tests :: Systeminfo Binding Tests SUCCESS [01:02 min]
```

**Comment by wborn** [comment]
> It was run from a Git Bash window.

It might cause Spotless to think you prefer Unix-like line endings while Git thinks you prefer DOS/Windows line endings.

See also the [Spotless line endings documentation](https://github.com/diffplug/spotless/tree/main/plugin-maven#line-endings-and-encodings-invisible-stuff):

> Git has opinions about line endings, and if Spotless and git disagree, then you're going to have a bad time.

The only increase in build times I have noticed is due to more add-ons having been merged recently.
I added some more options to the README that you can use to improve build times in https://github.com/openhab/openhab-addons/pull/8767.

Try disabling feature verification and a parallel build, e.g.:

`mvn clean install -DskipChecks=true -DskipTests=true -Dfeatures.verify.skip=true -Dspotless.check.skip=true -T 1C`

With that it only takes ~1 minute to build all add-ons on my machine.

**Comment by lolodomo** [comment]
I will try with CMD and Poweshell and then report.

**Comment by lolodomo** [comment]
The result (error) is the same if I use Windows PowerShell.

**Comment by rogierhofboer** [comment]
It seems if you checkout pom files with Linux \n file endings on Windows maven finds the file invalid (which I can imagine), but if you checkout with Windows line endings \r\n the spotless does think the file is invalid.

**Comment by wborn** [comment]
Looks like the `.gitattributes` wasn't added when Spotless was activated on the master/main branch. We already have this file on the 2.5.x branch, see: https://github.com/openhab/openhab-addons/blob/2.5.x/.gitattributes
I'll create some PRs to add it to this branch and the other projects.

**Comment by rogierhofboer** [comment]
@wborn Thanks! 
_Note: I just learned GIT_ATTRIBUTES' as line endings option is the default (and recommended) configuration for spotless._

**Comment by wborn** [comment]
I hope it also solves @lolodomo's issues. If you did not have them on the 2.5.x branch they should now be solved as well. :-)

**Comment by rogierhofboer** [comment]
It solves the problem for me :)

**Comment by lolodomo** [comment]
I updated my local repo but unfortunately I still have the same problem when I try to compile the main branch.

**Comment by rogierhofboer** [comment]
Damn sorry @wborn.... @lolodomo is correct..
I've retried with a full clean checkout and build and it fails again (with .gitattributes added by hand for openhab-core).

If it did work on 2.5.9, what else is different?

**Comment by rogierhofboer** [comment]
I think I know what might go wrong.
openhab-core/tools/static-code-analysis/checkstyle/ruleset.properties defines:

`checkstyle.headerCheck.content=^/\\*\\*$\\n^ \\* Copyright \\(c\\) {0}-{1} Contributors to the openHAB project$\\n^ \\*$\\n^ \\* See the NOTICE file\\(s\\) distributed with this work for additional$\\n^ \\* information.$\\n^ \\*$\\n^ \\* This program and the accompanying materials are made available under the$\\n^ \\* terms of the Eclipse Public License 2\\.0 which is available at$\\n^ \\* http://www.eclipse.org/legal/epl\\-2\\.0$\\n^ \\*$\\n^ \\* `

With explicit linux line endings...
This is also where I now get the error (which is different then before)

**Comment by wborn** [comment]
Perhaps there is one of the @openhab/add-ons-maintainers who uses Windows and can check if there are still Spotless issues on the main branch and what could fix them? I have no issues or easy ways to reproduce this on Ubuntu. :wink:

**Comment by rogierhofboer** [comment]
I don't think it is the openhab-core/tools/static-code-analysis/checkstyle/ruleset.properties  
\\n seems to work, changing it to \\r\\n gives pattern match errors. If addons do build I could check how they are configured.

**Comment by rogierhofboer** [comment]
For some reason spotless seems to ignore .gitattributes on master.
I am lost why it is. Even setting the value to crlf instead of auto does not make stop complaining line endings should be \n only.

**Comment by wborn** [comment]
Try the `main` branch instead of `master`. The `master` branch is no longer used.

**Comment by rogierhofboer** [comment]
openhab-core still uses master

**Comment by rogierhofboer** [comment]
https://github.com/diffplug/spotless/issues/540 related?
Looking into it...

**Comment by J-N-K** [comment]
I get the same error (on Win 10) if I start from the root-POM. Building single projects with `-pl` works. The interesting thing is, that `mvn clean install -rf :org.openhab.addons.reactor.bundles` also works.

**Comment by lolodomo** [comment]
I can confirm that build from inside a binding is working.
Problem is when you build from the repo root folder.

**Comment by J-N-K** [comment]
`git config core.eol=crlf` solves the problem. This is not a problem since `autcrlf=true` takes precendence and git's behaviour stays unchanged.

**Comment by nedtwigg** [comment]
You might want `* text eol=native`, see https://github.com/diffplug/spotless/issues/540

**Comment by hmerk** [comment]
Is this still an open issue ?

**Comment by wborn** [comment]
For me it works fine on Windows using:

```bash
git config --global core.autocrlf false
git config --global core.eol crlf
```

**Comment by lolodomo** [comment]
I have to test these settings.

**Comment by wborn** [comment]
If it works better we probably want to update the [developer docs](https://github.com/openhab/openhab-docs/blob/main/developers/index.md?plain=1#L132-L139) as well. Sometimes those `.gitattributes` changes end up in PRs by Windows contributors. :confused:

**Comment by lolodomo** [comment]
> For me it works fine on Windows using:
> 
> ```shell
> git config --global core.autocrlf false
> git config --global core.eol crlf
> ```

Tried and working. Thank you
