### ISSUE TITLE
[neeo] Can Not Add Brain - OH3

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#8984]
I'm running a fresh install of OH3 M2 and trying to migrate from OH2.  I have no issues on OH2 with the neeo binding.  When I try to add a brain on OH 3 I get the following error when trying to add a brain.

```
2020-11-08 18:50:13.177 [WARN ] [org.eclipse.jetty.server.HttpChannel] - /neeo/neeostatus/addbrain
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.io.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.io.neeo.internal.NeeoApi.getSystemInfo(NeeoApi.java:204) ~[?:?]
        at org.openhab.io.neeo.internal.discovery.MdnsBrainDiscovery.addDiscovered(MdnsBrainDiscovery.java:302) ~[?:?]
        at org.openhab.io.neeo.internal.discovery.MdnsBrainDiscovery.addDiscovered(MdnsBrainDiscovery.java:287) ~[?:?]
        at org.openhab.io.neeo.NeeoService.addBrain(NeeoService.java:526) ~[?:?]
        at org.openhab.io.neeo.internal.servletservices.BrainDashboardService.handlePost(BrainDashboardService.java:166) ~[?:?]
        at org.openhab.io.neeo.internal.AbstractServlet.doPost(AbstractServlet.java:151) ~[?:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[bundleFile:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[bundleFile:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544) ~[bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) ~[bundleFile:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307) ~[bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293) ~[bundleFile:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) ~[bundleFile:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.Server.handle(Server.java:494) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [bundleFile:9.4.20.v20190813]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 43 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 43 more

```

**Comment by morph166955** [comment]
Also on start I get:

```
2020-11-08 19:09:47.874 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.binding.neeo.internal.NeeoBrainApi.<init>(NeeoBrainApi.java:47) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.initializeTask(NeeoBrainHandler.java:167) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.lambda$0(NeeoBrainHandler.java:146) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more

```

**Comment by J-N-K** [comment]
Can you show `find-class javax.ws.rs.client.ClientBuilder` and `list | grep JAX-RS`? These classes should be available

**Comment by J-N-K** [comment]
Please try if `update org.openhab.binding.neeo https://janessa.me/esh/org.openhab.binding.neeo-3.0.0-SNAPSHOT.jar` solves your problem.

**Comment by morph166955** [comment]
Ok lots of info, let me try to break this out.

Installed the snapshot binding from J-N-K:
openhab> bundle:list -s | grep -i neeo
208 │ Active │  80 │ 3.0.0.202011111831      │ org.openhab.binding.neeo
261 │ Active │  80 │ 3.0.0.M2                │ org.openhab.io.neeo

Info as requested:
openhab> find-class javax.ws.rs.client.ClientBuilder

Apache Aries JAX-RS Specification API (45)
javax/ws/rs/client/ClientBuilder.class

Apache Aries JAX-RS Whiteboard (46)
javax/ws/rs/client/ClientBuilder.class

org.osgi:org.osgi.service.jaxrs (200)
javax/ws/rs/client/ClientBuilder.class

openHAB Add-ons :: Bundles :: Neeo Binding (208)
javax/ws/rs/client/ClientBuilder.class

openHAB Add-ons :: Bundles :: Remote openHAB Binding (237)
javax/ws/rs/client/ClientBuilder.class

openHAB Add-ons :: Bundles :: IO :: NEEO Integration (261)
javax/ws/rs/client/ClientBuilder.class
openhab> list | grep JAX-RS
 45 │ Active │  80 │ 1.0.1                   │ Apache Aries JAX-RS Specification API
 46 │ Active │  80 │ 1.0.9                   │ Apache Aries JAX-RS Whiteboard


Still no fix on the issue.  Restarted a few times.  Cleared the cache and restarted a few times.

On start:
2020-11-11 19:48:07.690 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.binding.neeo.internal.NeeoBrainApi.<init>(NeeoBrainApi.java:69) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.initializeTask(NeeoBrainHandler.java:172) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.lambda$0(NeeoBrainHandler.java:151) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
2020-11-11 19:48:07.697 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.binding.neeo.internal.NeeoBrainApi.<init>(NeeoBrainApi.java:69) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.initializeTask(NeeoBrainHandler.java:172) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.lambda$0(NeeoBrainHandler.java:151) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
2020-11-11 19:48:16.625 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.io.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.io.neeo.internal.NeeoApi.getSystemInfo(NeeoApi.java:204) ~[?:?]
        at org.openhab.io.neeo.internal.discovery.MdnsBrainDiscovery.considerService(MdnsBrainDiscovery.java:253) ~[?:?]
        at org.openhab.io.neeo.internal.discovery.MdnsBrainDiscovery.considerService(MdnsBrainDiscovery.java:219) ~[?:?]
        at org.openhab.io.neeo.internal.discovery.MdnsBrainDiscovery.lambda$0(MdnsBrainDiscovery.java:156) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 12 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 12 more

When I try to add a brain
2020-11-11 19:49:07.357 [WARN ] [org.eclipse.jetty.server.HttpChannel] - /neeo/neeostatus/addbrain
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.io.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.io.neeo.internal.NeeoApi.getSystemInfo(NeeoApi.java:204) ~[?:?]
        at org.openhab.io.neeo.internal.discovery.MdnsBrainDiscovery.addDiscovered(MdnsBrainDiscovery.java:302) ~[?:?]
        at org.openhab.io.neeo.internal.discovery.MdnsBrainDiscovery.addDiscovered(MdnsBrainDiscovery.java:287) ~[?:?]
        at org.openhab.io.neeo.NeeoService.addBrain(NeeoService.java:526) ~[?:?]
        at org.openhab.io.neeo.internal.servletservices.BrainDashboardService.handlePost(BrainDashboardService.java:166) ~[?:?]
        at org.openhab.io.neeo.internal.AbstractServlet.doPost(AbstractServlet.java:151) ~[?:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[bundleFile:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[bundleFile:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544) ~[bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) ~[bundleFile:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307) ~[bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293) ~[bundleFile:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) ~[bundleFile:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.Server.handle(Server.java:494) ~[bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [bundleFile:9.4.20.v20190813]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 43 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 43 more

**Comment by morph166955** [comment]
I'm pretty sure I am running your updated bundle.

openhab> list org.openhab.binding.neeo
START LEVEL 100 , List Threshold: 50
 ID │ State  │ Lvl │ Version            │ Name
────┼────────┼─────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
208 │ Active │  80 │ 3.0.0.202011111831 │ openHAB Add-ons :: Bundles :: Neeo Binding

**Comment by morph166955** [comment]
I ran it again just to be sure...

openhab> list org.openhab.binding.neeo
START LEVEL 100 , List Threshold: 50
 ID │ State  │ Lvl │ Version            │ Name
────┼────────┼─────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
208 │ Active │  80 │ 3.0.0.202011111831 │ openHAB Add-ons :: Bundles :: Neeo Binding
openhab> update org.openhab.binding.neeo https://janessa.me/esh/org.openhab.binding.neeo-3.0.0-SNAPSHOT.jar
openhab> list org.openhab.binding.neeo
START LEVEL 100 , List Threshold: 50
 ID │ State  │ Lvl │ Version            │ Name
────┼────────┼─────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
208 │ Active │  80 │ 3.0.0.202011111831 │ openHAB Add-ons :: Bundles :: Neeo Binding

And on restart...

2020-11-11 20:17:52.136 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.binding.neeo.internal.NeeoBrainApi.<init>(NeeoBrainApi.java:69) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.initializeTask(NeeoBrainHandler.java:172) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.lambda$0(NeeoBrainHandler.java:151) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
2020-11-11 20:17:52.139 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.binding.neeo.internal.NeeoBrainApi.<init>(NeeoBrainApi.java:69) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.initializeTask(NeeoBrainHandler.java:172) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.lambda$0(NeeoBrainHandler.java:151) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more

**Comment by morph166955** [comment]
Do I need the updated IO transport from you as well?

openhab> list org.openhab.io.neeo
START LEVEL 100 , List Threshold: 50
 ID │ State  │ Lvl │ Version  │ Name
────┼────────┼─────┼──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
261 │ Active │  80 │ 3.0.0.M2 │ openHAB Add-ons :: Bundles :: IO :: NEEO Integration

**Comment by J-N-K** [comment]
I guess that needs the same fix. Didn‘t see it was in there, too. Will check tomorrow.

**Comment by morph166955** [comment]
Just as a test, I removed the IO completely and I still get the first two errors on startup.  I do not get the third error anymore (which makes sense because the first two showed on binding.neeo and the third was on io.neeo).

openhab> list org.openhab.io.neeo
START LEVEL 100 , List Threshold: 50
ID │ State │ Lvl │ Version │ Name
───┼───────┼─────┼─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
openhab> list org.openhab.binding.neeo
START LEVEL 100 , List Threshold: 50
 ID │ State  │ Lvl │ Version            │ Name
────┼────────┼─────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
208 │ Active │  80 │ 3.0.0.202011111831 │ openHAB Add-ons :: Bundles :: Neeo Binding
openhab>

2020-11-11 20:37:04.872 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.binding.neeo.internal.NeeoBrainApi.<init>(NeeoBrainApi.java:69) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.initializeTask(NeeoBrainHandler.java:172) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.lambda$0(NeeoBrainHandler.java:151) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
2020-11-11 20:37:04.879 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:55) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.<init>(HttpRequest.java:51) ~[?:?]
        at org.openhab.binding.neeo.internal.NeeoBrainApi.<init>(NeeoBrainApi.java:69) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.initializeTask(NeeoBrainHandler.java:172) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoBrainHandler.lambda$0(NeeoBrainHandler.java:151) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more
Caused by: java.lang.InstantiationException
        at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[?:?]
        at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[?:?]
        at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[?:?]
        ... 11 more

**Comment by J-N-K** [comment]
Ok. Next try. Please update. There is also an updated bundle for io.neeo available, just exchange `binding.neeo` with `io.neeo`

**Comment by morph166955** [comment]
I'll give a hesitant yes that this worked.  There were no errors on start.  I can see both my Neeo brains in the web portal as well.  I will need to update my Neeo remotes to use the OH3 install I have to confirm that the whole thing is working as expected.  

openhab> bundle:list -s | grep neeo
262 x Active x  80 x 3.0.0.M2                x org.openhab.binding.neeo
263 x Active x  80 x 3.0.0.M2                x org.openhab.io.neeo
openhab> update org.openhab.binding.neeo https://janessa.me/esh/org.openhab.binding.neeo-3.0.0-SNAPSHOT.jar
openhab> update org.openhab.io.neeo https://janessa.me/esh/org.openhab.io.neeo-3.0.0-SNAPSHOT.jar                                                                                                                                    
openhab> bundle:list -s | grep neeo
262 x Active x  80 x 3.0.0.202011121116      x org.openhab.binding.neeo
263 x Active x  80 x 3.0.0.202011121113      x org.openhab.io.neeo
openhab>

**Comment by J-N-K** [comment]
Just give an ok here when you are ready and everything works. Then we can merge the PR.

**Comment by morph166955** [comment]
Sounds good.  I will likely just run a test or two to see if this works as opposed to doing the full cut.  I haven't migrated my production use off to the OH3 install yet so I don't want to completely break things yet.

**Comment by J-N-K** [comment]
At least this new version is no worse than the old one and fixes the CNFE.

**Comment by morph166955** [comment]
So let's break this in half.  I believe the original issue is fixed.  I'm able to add brains, create devices, and push them to the brain.  

I now however get other error messages.  If I'm reading this correctly, when I pushed the power off button for the TV on the remote, the brain sent this to OH.  

2020-11-12 21:40:28.515 [DEBUG] [al.handler.NeeoForwardActionsServlet] - handleForwardActions {"action":"poweroff","device":"Top TV","room":"Theater","recipe":"Top TV"}
2020-11-12 21:40:28.517 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {true}WebClient has thrown exception, unwinding now
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:113) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:126) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:505) ~[bundleFile:1.0.9]
        at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:47) ~[bundleFile:1.0.9]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:705) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.post(SyncInvokerImpl.java:85) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:153) [bundleFile:1.0.9]
        at org.openhab.binding.neeo.internal.net.HttpRequest.sendPostJsonCommand(HttpRequest.java:95) [bundleFile:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:106) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-11-12 21:40:28.518 [DEBUG] [al.handler.NeeoForwardActionsServlet] - Cannot forward event {"action":"poweroff","device":"Top TV","room":"Theater","recipe":"Top TV"} to true: 503
2020-11-12 21:40:28.518 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[?:?]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.close(URLConnectionHTTPConduit.java:100) ~[?:?]
        at org.apache.cxf.endpoint.AbstractConduitSelector.close(AbstractConduitSelector.java:77) ~[?:?]
        at org.apache.cxf.jaxrs.client.AbstractClient.close(AbstractClient.java:360) ~[?:?]
        at org.apache.cxf.jaxrs.client.spec.ClientImpl.close(ClientImpl.java:90) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.close(HttpRequest.java:111) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:113) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by J-N-K** [comment]
Please `log:set TRACE org.openhab.binding.neeo.internal.net.HttpRequest` and update the binding (io-bundle is unchanged). This will most likely still show the error, but we should see what URI is causing the problems.

**Comment by morph166955** [comment]
Here ya go...  TV was turned off, then on, then off again.

```
openhab> bundle:list -s | grep neeo
262 │ Active │  80 │ 3.0.0.202011121116      │ org.openhab.binding.neeo
263 │ Active │  80 │ 3.0.0.202011121113      │ org.openhab.io.neeo
openhab> update org.openhab.binding.neeo https://janessa.me/esh/org.openhab.binding.neeo-3.0.0-SNAPSHOT.jar
openhab> bundle:list -s | grep neeo
262 │ Active │  80 │ 3.0.0.202011131826      │ org.openhab.binding.neeo
263 │ Active │  80 │ 3.0.0.202011121113      │ org.openhab.io.neeo
openhab>


2020-11-14 01:59:51.020 [TRACE] [inding.neeo.internal.net.HttpRequest] - sendPostJsonCommand: target=true, body={"action":"poweroff","device":"Top TV","room":"Theater","recipe":"Top TV"}
2020-11-14 01:59:51.024 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {true}WebClient has thrown exception, unwinding now
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:113) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:126) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:505) ~[bundleFile:1.0.9]
        at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:47) ~[bundleFile:1.0.9]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:705) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.post(SyncInvokerImpl.java:85) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:153) [bundleFile:1.0.9]
        at org.openhab.binding.neeo.internal.net.HttpRequest.sendPostJsonCommand(HttpRequest.java:97) [bundleFile:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:105) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-11-14 01:59:51.025 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[?:?]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.close(URLConnectionHTTPConduit.java:100) ~[?:?]
        at org.apache.cxf.endpoint.AbstractConduitSelector.close(AbstractConduitSelector.java:77) ~[?:?]
        at org.apache.cxf.jaxrs.client.AbstractClient.close(AbstractClient.java:360) ~[?:?]
        at org.apache.cxf.jaxrs.client.spec.ClientImpl.close(ClientImpl.java:90) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.close(HttpRequest.java:113) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:112) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]



2020-11-14 02:00:24.660 [TRACE] [inding.neeo.internal.net.HttpRequest] - sendPostJsonCommand: target=true, body={"action":"launch","device":"Top TV","room":"Theater","recipe":"Top TV"}
2020-11-14 02:00:24.661 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {true}WebClient has thrown exception, unwinding now
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:113) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:126) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:505) ~[bundleFile:1.0.9]
        at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:47) ~[bundleFile:1.0.9]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:705) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.post(SyncInvokerImpl.java:85) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:153) [bundleFile:1.0.9]
        at org.openhab.binding.neeo.internal.net.HttpRequest.sendPostJsonCommand(HttpRequest.java:97) [bundleFile:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:105) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-11-14 02:00:24.662 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[?:?]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.close(URLConnectionHTTPConduit.java:100) ~[?:?]
        at org.apache.cxf.endpoint.AbstractConduitSelector.close(AbstractConduitSelector.java:77) ~[?:?]
        at org.apache.cxf.jaxrs.client.AbstractClient.close(AbstractClient.java:360) ~[?:?]
        at org.apache.cxf.jaxrs.client.spec.ClientImpl.close(ClientImpl.java:90) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.close(HttpRequest.java:113) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:112) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]



2020-11-14 02:00:45.384 [TRACE] [inding.neeo.internal.net.HttpRequest] - sendPostJsonCommand: target=true, body={"action":"poweroff","device":"Top TV","room":"Theater","recipe":"Top TV"}
2020-11-14 02:00:45.386 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {true}WebClient has thrown exception, unwinding now
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:113) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:126) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:505) ~[bundleFile:1.0.9]
        at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:47) ~[bundleFile:1.0.9]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:705) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.post(SyncInvokerImpl.java:85) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:153) [bundleFile:1.0.9]
        at org.openhab.binding.neeo.internal.net.HttpRequest.sendPostJsonCommand(HttpRequest.java:97) [bundleFile:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:105) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-11-14 02:00:45.388 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[?:?]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.close(URLConnectionHTTPConduit.java:100) ~[?:?]
        at org.apache.cxf.endpoint.AbstractConduitSelector.close(AbstractConduitSelector.java:77) ~[?:?]
        at org.apache.cxf.jaxrs.client.AbstractClient.close(AbstractClient.java:360) ~[?:?]
        at org.apache.cxf.jaxrs.client.spec.ClientImpl.close(ClientImpl.java:90) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.close(HttpRequest.java:113) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:112) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by J-N-K** [comment]
Looks like a configuration issue. Somehow `forwardChain` seems to be `true` while it should be an URL (at least that's in the documentation). Can you check that?

**Comment by morph166955** [comment]
Do you have any idea from the code where that config may be?  I can't find anything that's just set to true or configured to be a url on my side. I also have no idea what url that would need to be set to either.

**Comment by J-N-K** [comment]
https://www.openhab.org/addons/bindings/neeo/#neeo-brain

`forwardChain` somehow evaluates to `true`

**Comment by morph166955** [comment]
The only option I have configured under the thing is ipAddress. I can try to manually set them blank, i just never did as they aren't required fields.

**Comment by morph166955** [comment]
Why is this closed?

**Comment by wborn** [comment]
Because it should be fixed now #9006 got merged. :rocket:

**Comment by morph166955** [comment]
Ok. Ill open a separate bug up for the URL issue and reference this.
