### ISSUE TITLE
[netatmo] items returning to default state

### ISSUE THREAD

**Issue by soth78** [openhab/openhab-addons#9004]
Hi,

I'm using the latest openhab (2.5.10-1) totally updated. For some time now, the netatmo thermostat controls have a strange behavior, for example:

- I change the mode to "off"
- The thermostat turns off
- BasicUI item turns off, and after a second turns back to program
- thermostat is still off

Could you please advice? logs doesn't show much:

2020-11-11 16:09:57.261 [ome.event.ItemCommandEvent] - Item 'Termostato_SetpointMode' received command off
2020-11-11 16:09:57.287 [nt.ItemStatePredictedEvent] - Termostato_SetpointMode predicted to become off
2020-11-11 16:09:57.316 [thome.event.ItemStateEvent] - Termostato_SetpointMode updated to off
2020-11-11 16:09:57.320 [vent.ItemStateChangedEvent] - Termostato_SetpointMode changed from program to off
2020-11-11 16:09:59.474 [event.ThingStatusInfoEvent] - 'netatmo:netatmoapi:c758c303' updated: ONLINE
2020-11-11 16:09:59.481 [event.ThingStatusInfoEvent] - 'netatmo:NAPlug:c758c303:70ee500be9e2' updated: ONLINE
2020-11-11 16:09:59.492 [event.ThingStatusInfoEvent] - 'netatmo:NATherm1:c758c303:0400000c897a' updated: ONLINE
2020-11-11 16:09:59.500 [thome.event.ItemStateEvent] - Termostato_Temperature updated to 23.5
2020-11-11 16:09:59.512 [thome.event.ItemStateEvent] - Termostato_Setpoint updated to 22.00
2020-11-11 16:09:59.531 [thome.event.ItemStateEvent] - Termostato_SetpointMode updated to program
2020-11-11 16:09:59.538 [thome.event.ItemStateEvent] - Nivel_Bateria updated to 41.00
2020-11-11 16:09:59.543 [vent.ItemStateChangedEvent] - Termostato_SetpointMode changed from off to program

I'm using openhab on Chrome (BasicUI) and Android (same basicUI) and some time ago this was working perfectly, don't know what changed to be honest

Thank you!

**Comment by soth78** [comment]
Hi,

Updated to the latest openhab and openhab-addons right now, still issue persists.

If I change from program to manual, it goes back (expected I think):
2020-12-16 17:43:42.789 [ome.event.ItemCommandEvent] - Item 'Termostato_SetpointMode' received command manual
2020-12-16 17:43:42.818 [nt.ItemStatePredictedEvent] - Termostato_SetpointMode predicted to become manual
2020-12-16 17:43:42.843 [thome.event.ItemStateEvent] - Termostato_SetpointMode updated to manual

==> /var/log/openhab2/openhab.log <==

2020-12-16 17:43:42.848 [INFO ] [.internal.thermostat.NATherm1Handler] - Switching to manual mode is done by assigning a setpoint temperature - command dropped

==> /var/log/openhab2/events.log <==
2020-12-16 17:43:42.861 [thome.event.ItemStateEvent] - Termostato_SetpointMode updated to program
2020-12-16 17:43:42.875 [vent.ItemStateChangedEvent] - Termostato_SetpointMode changed from program to manual
2020-12-16 17:43:42.878 [vent.ItemStateChangedEvent] - Termostato_SetpointMode changed from manual to program


But, when doing this by changing the temperature, same thing, it send the data to the API, but on openhab it goes back to program when it shouldn't:

2020-12-16 17:45:32.892 [ome.event.ItemCommandEvent] - Item 'Termostato_Setpoint' received command 20.5 °C
2020-12-16 17:45:32.917 [nt.ItemStatePredictedEvent] - Termostato_Setpoint predicted to become 20.5 °C
2020-12-16 17:45:32.956 [thome.event.ItemStateEvent] - Termostato_Setpoint updated to 20.5 °C
2020-12-16 17:45:32.983 [vent.ItemStateChangedEvent] - Termostato_Setpoint changed from 22.0 °C to 20.5 °C
2020-12-16 17:45:35.727 [event.ThingStatusInfoEvent] - 'netatmo:netatmoapi:c758c303' updated: ONLINE
2020-12-16 17:45:35.731 [event.ThingStatusInfoEvent] - 'netatmo:NAPlug:c758c303:70ee500be9e2' updated: ONLINE
2020-12-16 17:45:35.736 [event.ThingStatusInfoEvent] - 'netatmo:NATherm1:c758c303:0400000c897a' updated: ONLINE
2020-12-16 17:45:35.742 [thome.event.ItemStateEvent] - Termostato_Temperature updated to 22.3999996185302734375
2020-12-16 17:45:35.750 [thome.event.ItemStateEvent] - Termostato_Setpoint updated to 22.00
2020-12-16 17:45:35.762 [thome.event.ItemStateEvent] - Termostato_SetpointMode updated to program
2020-12-16 17:45:35.831 [vent.ItemStateChangedEvent] - Termostato_Setpoint changed from 20.5 °C to 22.0 °C


Can someone help me out please?

**Comment by clinique** [comment]
Currently working on a complete revamp of this binding

**Comment by soth78** [comment]
Great to know, thank you! any expected date of release @clinique ?

**Comment by clinique** [comment]
Work is in progress, bigger than expected because : 

- I removed all external dependencies 
- had to push a modification in core in order to work properly with Netatmo oAuth,
- revamped many things as swagger was putting big overhead on code that became very complicated

It will be a breaking change PR. But now that OH3 is here, it's so easy to create things and items :)

**Comment by clinique** [comment]
Addressed in [this PR](https://github.com/openhab/openhab-addons/pull/9486)

**Comment by lolodomo** [comment]
@soth78 : as the Netatmo binding was largely revamped, please try again with the new version and reopen this issue in case your problem is not resolved.
