### ISSUE TITLE
[netatmo] NATherm1 wrong temperature at frost-guard setpoint

### ISSUE THREAD

**Issue by d5c0d3** [openhab/openhab-addons#9045]
## Expected Behavior
when changing the setpoint mode to frost-guard i expect the temperature to be the set frost-guard temperature (7°C)

## Current Behavior
When changing the setpoint mode to frost-guard the temperature at the Thermostat itself is set correctly to the expected 7°C . However openhab shows 22.5 °C. 

## Possible Solution
is it necessary to include some kind of correction?

## Context
As this wrong displayed temperature is also written to my influxdb persistence instance it is logged incorrectly. Eventually visualization of the data is wrong and I can't use this wrong number for calculations.

## Your Environment
Openhabian @ Linux openhab 5.4.72-v7l+ #1356 2020 armv7l
OpenHAB 2.5.10 (Build)
binding-netatmo - 2.5.10

**Comment by lolodomo** [comment]
Can you show how are defined your 2 items?

**Comment by lolodomo** [comment]
@clinique : that is for you.

**Comment by clinique** [comment]
@lolodomo : I'm starting a review of the netatmo binding to address opened issues and polish it in regard of OH3. I'm facing problems in the IDE regarding code generation of the swagger and missing okio dependencies. Did you faced the same ? I maven updated/ maven generate sources / maven install... without success.

**Comment by lolodomo** [comment]
No, it works for me. I believe I am first running a maven build outside of Eclipse.
Then in Eclipse the only specific thing I have to do after importing the maven project is to add the source folder of the generated sources.

**Comment by clinique** [comment]
...wip in progress 85% done.

**Comment by clinique** [comment]
Addressed in [this PR](https://github.com/openhab/openhab-addons/pull/9486)

**Comment by lolodomo** [comment]
@d5c0d3 : as the Netatmo binding was largely revamped, please try again with the new version and reopen this issue in case your problem is not resolved.
