### ISSUE TITLE
[netatmo] NATherm1 Thing OFFLINE after firmware update

### ISSUE THREAD

**Issue by AntaresTeo** [openhab/openhab-addons#9875]
## Expected Behavior
Good morning,
I have a Netatmo thermostat and I have received an update to the relay firmware (going from release 210 to 222) and to the thermostat itself (going from 72 to 75). After this update, the Thing relating to the thermostat is OFFLINE. I have a second thermostat that hasn’t received the update yet but it works fine. 

## Current Behavior
In the openhab.log file I have the following exception: 

> java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 1 column 233 path $.body.devices[0].plug_connected_boiler

## Possible Solution
Change the type from INT to BOOLEAN according to the firmware release.

## Steps to Reproduce (for Bugs)
Check the Thing status with the release 75 of Thermostat firmware.

## Your Environment
Openhabian @ Raspian GNU/Linux 10, kernel 5.4.83+ #1379 2020 armv6l
OpenHAB 3.0.0 (Build)
binding-netatmo - 3.0.0

**Comment by clinique** [comment]
Addressed in [this PR](https://github.com/openhab/openhab-addons/pull/9486)

**Comment by lolodomo** [comment]
@AntaresTeo : as the Netatmo binding was largely revamped, please try again with the new version and reopen this issue in case your problem is not resolved.
