### ISSUE TITLE
Homematic Binding - SAXNotRecognizedException

### ISSUE THREAD

**Issue by genaumann** [openhab/openhab-addons#9971]
Hey,

since openhab addons 3.0.1, I get a communication error on my Homematic Bridge Thing. I am not able to use my Homematic devices in openhab anymore.
After upgrading from 3.0.0 to 3.0.1 I get the following error:

`org.xml.sax.SAXNotRecognizedException: Feature 'https://xml.org/sax/features/external-general-entities' is not recognized.`

The linked webpage on xml.org isn't available (anymore?).

## Your Environment

* Version used: openhab 3.0.0-1, openhab-addons 3.0.1-1
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspi OS with manual Openhab installation

**Comment by kaikreuzer** [comment]
Sorry, that was indeed an erroneous build - it has been wiped again and a new one is done today (I'll make sure to do 3.0.1-2 linux packages, so that the update is pulled for you).

**Comment by kaikreuzer** [comment]
Build is fixed, issue should be gone!

**Comment by CSchlipp** [comment]
Just pulled the latest docker image, but this issue still persists.

**Comment by kaikreuzer** [comment]
I'm not using docker, but I guess it won't automatically reinstall bindings. Try to deinstall the binding once, so that the correct jar is loaded.

**Comment by CSchlipp** [comment]
That didn't help either, sorry. Even tried with a restart in between.

**Comment by kaikreuzer** [comment]
Try to figure out where docker stores the downloaded artifacts and wipe them there. Maybe @wborn knows by heart how to do that.

**Comment by wborn** [comment]
This might be one of the rare moments where it does make sense to wipe the cache. :wink: I.e. stop the container and remove the content from your container volume directories that map to the `/openhab/userdata/cache` and `/openhab/userdata/tmp` directories in the container.

**Comment by CSchlipp** [comment]
Uh, the previous "3.0.1" version was still cached in the maven repository located at openhab_userdata/tmp/mvn/org/openhab/addons/bundles/org.openhab.binding.homematic/ (that's even persisted outside of the container)

After deleting everything in there and reinstalling the binding, it seems to work again. 
Just wonder how many other bindings may face the same issue?

**Comment by SynPrime** [comment]
The APT-Package version 3.0.1-2 fixed this issue for me. Thanks for your fast bugfix
